name: Compilar APK Flet

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flet

      - name: Preparar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Preparar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Compilar APK con Flet
        # ¡AQUÍ ESTÁ LA MAGIA! Responderá "Y" automáticamente a todo.
        run: yes | flet build apk

      - name: Subir APK final
        uses: actions/upload-artifact@v4
        with:
          name: SignalMapper-APK
          path: build/apk/**/*.apk
