name: Compilar APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install flet
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - name: Build APK
        # ✅ Solo 'location' es una opción válida aquí
        run: yes | flet build apk --permissions location
      - uses: actions/upload-artifact@v4
        with:
          name: SignalMapper-APK
          path: build/apk/**/*.apk
