name: Compilar APK Final

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install flet flet-geolocator
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - name: Limpiar y Compilar
        # Usamos el flag --clear-cache para evitar el bug de 'Unknown control: Geolocator'
        run: yes | flet build apk --permissions location --clear-cache
      - uses: actions/upload-artifact@v4
        with:
          name: SignalMapper-APK
          path: build/apk/**/*.apk
